description: This playbook deploys and configures deployment packages on a target
  server.
id: Auto Deploy - Standalone
inputs: []
name: Auto Deploy - Standalone
outputs: []
quiet: true
sourceplaybookid: ed37203c-ffb6-4d5f-8cf2-d88c1ebb621b
starttaskid: "0"
tags:
- auto-deploy
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 885c82bd-5f40-4912-889f-02e0509cf693
      iscommand: false
      name: ""
      version: -1
    taskid: 885c82bd-5f40-4912-889f-02e0509cf693
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 04b9d546-cf4c-4b0b-8d04-3c560551150e
      iscommand: false
      name: Initialize Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 04b9d546-cf4c-4b0b-8d04-3c560551150e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "13":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Online Packages
        options: []
        optionsarg:
        - simple: Phishing Report
        placeholder: ""
        readonly: false
        required: false
        tooltip: Package names available online
        type: multiSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Package Files
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: Upload package files for the deployment
        type: attachments
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Package File Password
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: Zip password for decryption
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "3"
        label: ""
        labelarg:
          simple: Core REST API instance
        options: []
        optionsarg:
        - complex:
            accessor: name
            filters:
            - - left:
                  iscontext: true
                  value:
                    simple: modules.brand
                operator: isEqualString
                right:
                  value:
                    simple: Core REST API
            - - left:
                  iscontext: true
                  value:
                    simple: modules.state
                operator: isEqualString
                right:
                  value:
                    simple: active
            root: modules
        placeholder: ""
        readonly: false
        required: true
        tooltip: Name of the Core REST API integration instance used to connect to
          the target tenant.
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "4"
        label: ""
        labelarg:
          simple: Update Installed Content Packs
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: true
        tooltip: Install the latest content packs when updates are available.
        type: singleSelect
      sender: ""
      title: Deployment Configuration
      totalanswers: 0
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Enter Deployment Configuration
      cc: null
      format: ""
      methods: []
      subject: {}
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 62c66de8-85e6-4049-867e-411da3a6a4fa
      iscommand: false
      name: Enter Deployment Configuration
      type: collection
      version: -1
    taskid: 62c66de8-85e6-4049-867e-411da3a6a4fa
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      APIInstance:
        complex:
          accessor: "3"
          root: Deployment Configuration.Answers
      PackageFileEntryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Name
              operator: in
              right:
                iscontext: true
                value:
                  simple: DeploymentPackageFileName
          root: File
      PackageFilePassword:
        complex:
          accessor: "2"
          root: Deployment Configuration.Answers
      UpdateInstalledPacks:
        complex:
          accessor: "4"
          root: Deployment Configuration.Answers
          transformers:
          - operator: toLowerCase
          - args:
              dt:
                value:
                  simple: .=val == "yes"
            operator: DT
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 1d6ced19-57a9-4b9c-8f7f-910ed7209445
      iscommand: false
      name: Deployment Process
      playbookId: 'Auto Deploy - M: Deployment Process'
      type: playbook
      version: -1
    taskid: 1d6ced19-57a9-4b9c-8f7f-910ed7209445
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1535
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 2
    scriptarguments:
      filename:
        complex:
          accessor: "0"
          root: Deployment Configuration.Answers
          transformers:
          - args:
              prefix: {}
              suffix:
                value:
                  simple: .zip
            operator: concat
      method:
        simple: GET
      save_as_file:
        simple: "yes"
      url:
        complex:
          accessor: "0"
          root: Deployment Configuration.Answers
          transformers:
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: _
              toReplace:
                value:
                  simple: ' '
            operator: replace
          - operator: toLowerCase
          - args:
              prefix:
                value:
                  simple: https://github.com/spearmin10/xsoar-utils/blob/main/auto-deploy/packages/
              suffix:
                value:
                  simple: .zip?raw=true
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a HTTP request with advanced capabilities
      id: 8969d2cc-b1d7-4b3d-8856-61245c6460ad
      iscommand: false
      name: Download package files
      script: HttpV2
      type: regular
      version: -1
    taskid: 8969d2cc-b1d7-4b3d-8856-61245c6460ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: Deployment Configuration.Answers
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9221c1fb-a170-466c-8f6a-ef8b3e233220
      iscommand: false
      name: Need to download packages online?
      type: condition
      version: -1
    taskid: 9221c1fb-a170-466c-8f6a-ef8b3e233220
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 865
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: DeploymentPackageFileName
      value:
        complex:
          accessor: "0"
          root: Deployment Configuration.Answers
          transformers:
          - args:
              prefix: {}
              suffix:
                value:
                  simple: .zip
            operator: concat
          - args:
              empty_values:
                value:
                  simple: .zip
              remove_keys: {}
            operator: RemoveEmpty
          - args:
              item:
                iscontext: true
                value:
                  simple: Deployment Configuration.Answers.1.Name
              raw: {}
            operator: AppendIfNotEmpty
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex XSOAR
        6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: 4737f1f4-0631-4423-8ad6-f2e8bb4a9585
      iscommand: false
      name: Set package files
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 4737f1f4-0631-4423-8ad6-f2e8bb4a9585
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1215
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4b3c856c-ebd0-44b4-8333-1fbadff02787
      iscommand: false
      name: Prepare Packages
      type: title
      version: -1
    taskid: 4b3c856c-ebd0-44b4-8333-1fbadff02787
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9a399f2b-b13d-48a2-8900-0ce4abb93533
      iscommand: false
      name: Deployment
      type: title
      version: -1
    taskid: 9a399f2b-b13d-48a2-8900-0ce4abb93533
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1390
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: Deployment Configuration.Answers
          operator: isNotEmpty
        - left:
            iscontext: true
            value:
              complex:
                accessor: "1"
                root: Deployment Configuration.Answers
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 201a1f3c-dc9c-4854-82b6-2b848c2f4340
      iscommand: false
      name: Are package names or files provided?
      type: condition
      version: -1
    taskid: 201a1f3c-dc9c-4854-82b6-2b848c2f4340
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2aff1d1e-9a05-4557-8d0f-0d4e95f66171
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2aff1d1e-9a05-4557-8d0f-0d4e95f66171
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
